### ISSUE TITLE
Migrate source to Swift 3.0

### ISSUE THREAD

**Issue by akashivskyy** [netguru/ResponseDetective#13]
Source files should be migrated to Swift 3.0. API should be updated to conform to Swift API Guidelines, potentially breaking source compatibility. ¯_(ツ)_/¯

**Comment by sxua** [comment]
Hi guys, do you have any ETA for Swift 3 compatible version?

**Comment by akashivskyy** [comment]
No, but I think we'll start working on that next week. I'll keep you updated. 🙂

**Comment by serejahh** [comment]
Hi @akashivskyy! I'm working on the issue. Existing code base is already migrated, now I'm fixing tests and then I'm gonna update API to be more Swifty. While fixing tests, I got a failed `ConsoleOutputFacilitySpec` tests. As far as I understood you rely on objects order in dictionary. It fails because headers have different order:
actual:
```
"X-Baz": "qux"
"X-Foo": "bar",
```
expected:
```
"X-Foo": "bar",
"X-Baz": "qux"
```

**Comment by akashivskyy** [comment]
>I'm working on the issue. Existing code base is already migrated, now I'm fixing tests and then I'm gonna update API to be more Swifty.

Fantastic! ✨ 

>As far as I understood you rely on objects order in dictionary. It fails because headers have different order:

Yeah, I agree that was kind of dumb on my side. If you'd like to change how the test behaves, feel free to do so. 😉
