### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by cakewalker56** [netguru/ResponseDetective#62]
Hi

**Comment by akashivskyy** [comment]
Hello there! Is there a problem you're experiencing with ResponseDetective?

I see this is your first GitHub issue ever. Please keep in mind that this is not a chat or a discussion forum. This is more like a tracker of bugs and features. Opening such issues in other, bigger repositories will probably cause it to be immediately closed and/or your account reported for spamming.

Next time, please try to specify your problem immediately in the description, instead of just writing "hi". 😉

**Comment by akashivskyy** [comment]
I'm going to close this issue but feel free to reopen it if you have something more to share.
